# Generated by Django 4.0.2 on 2022-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
